zadatak 2
draganakrstic1206/JavaZadaci pull request #1
Opened 2018-12-05 10:48 UTC by draganakrstic1206

2018-12-05 12:15 UTC, endavamarko requested changes

2018-12-05 12:15 UTC, endavamarko commented on src/Zadatak2.java
> +        unos.close();
ovo treba uraditi na kraju main metode, zatvaranje skener promenljive

2018-12-13 10:11 UTC, merged

2018-12-13 11:29 UTC, darkojovanovic commented on src/Zadatak2.java
> +                int kolicnik=a/b;
Kolicnik treba da bude tipa double

2018-12-13 11:52 UTC, draganakrstic1206 commented
zadatak je ispravljen i na master grani.